service: nerdwork-comic-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}
    DATABASE_URL: ${ssm:/nerdwork/${self:provider.stage}/database-url}
    JWT_SECRET: ${ssm:/nerdwork/${self:provider.stage}/jwt-secret}
    S3_BUCKET_NAME: ${ssm:/nerdwork/${self:provider.stage}/s3-bucket-name}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rds-data:ExecuteStatement
            - rds-data:BatchExecuteStatement
            - rds-data:BeginTransaction
            - rds-data:CommitTransaction
            - rds-data:RollbackTransaction
          Resource: "*"
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: 
            - "arn:aws:s3:::${ssm:/nerdwork/${self:provider.stage}/s3-bucket-name}/*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  comic:
    handler: src/lambda.handler
    events:
      - http:
          path: /comics/{proxy+}
          method: ANY
          cors: true
      - http:
          path: /comics
          method: ANY
          cors: true
    environment:
      STAGE: ${self:provider.stage}

custom:
  serverless-offline:
    httpPort: 3003
    noPrependStageInUrl: true