service: nerdwork-event-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}
    DATABASE_URL: ${ssm:/nerdwork/${self:provider.stage}/database-url}
    JWT_SECRET: ${ssm:/nerdwork/${self:provider.stage}/jwt-secret}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rds-data:ExecuteStatement
            - rds-data:BatchExecuteStatement
            - rds-data:BeginTransaction
            - rds-data:CommitTransaction
            - rds-data:RollbackTransaction
          Resource: "*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  event:
    handler: src/lambda.handler
    events:
      - http:
          path: /events/{proxy+}
          method: ANY
          cors: true
      - http:
          path: /events
          method: ANY
          cors: true
    environment:
      STAGE: ${self:provider.stage}

custom:
  serverless-offline:
    httpPort: 3005
    noPrependStageInUrl: true