#name: Deploy Infra (CDK)

#on:
 # push:
  #  branches: [main, "feat/*", "fix/*"]
   # paths:
    #  - 'infra/**'
     # - '.github/workflows/deploy-infra.yml'
  #workflow_dispatch: {}

#jobs:
 # deploy:
  #  name: Deploy CDK Stack
   # runs-on: ubuntu-latest
   # environment: production  # Optional: Add GitHub environment for approval
    #env:
     # AWS_REGION: eu-east-1

    #steps:
     # - name: Checkout code
      #  uses: actions/checkout@v4
     # - name: Setup pnpm
      #  uses: pnpm/action-setup@v2
       # with:
        #  version: 8
         # cache: 'pnpm'
      #- name: Setup Node.js
       # uses: actions/setup-node@v4
        #with:
         # node-version: '18'
          #cache: 'pnpm'
      #- name: Install dependencies
       # run: pnpm install
      #- name: Configure AWS credentials
       # uses: aws-actions/configure-aws-credentials@v4
        #with:
         # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws-region: eu-east-1
      #- name: Deploy AuthStack
       # run: pnpm --filter infra exec cdk deploy AuthStack --require-approval never
      #- name: Notify deployment status (GitHub check)
       # if: success()
        #run: |
         # echo "✅ AuthStack deployed successfully" >> $GITHUB_STEP_SUMMARY
      #- name: Notify deployment failure (GitHub check)
       # if: failure()
        #run: |
         # echo "❌ AuthStack deployment failed. Check logs." >> $GITHUB_STEP_SUMMARY